name: DevOps Auto Pipeline

on:
  push:
    branches: [ "main", "feature/**" ]

jobs:
  build-and-deploy:
    # 引用中央仓库定义的标准工作流
    uses: zentrix566/my-devops-core/.github/workflows/standard-build.yml@main
    with:
      # 这里必须改成 service_name，因为 standard-build.yml 里定义的是这个名字
      service_name: "{{APP_NAME}}"
    secrets:
      inherit